# Generated by Django 4.2.1 on 2023-06-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('months', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.AddField(
            model_name='month',
            name='tags',
            field=models.ManyToManyField(to='months.tag'),
        ),
    ]
