# Generated by Django 4.2.1 on 2023-06-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('months', '0002_tag_delete_catalog_month_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='tags',
        ),
        migrations.AddField(
            model_name='month',
            name='extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='month',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='month',
            name='expenses',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='month',
            name='income',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
