# Generated by Django 4.2.1 on 2023-06-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('months', '0003_remove_month_tags_month_extra_month_fixed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
